### ISSUE TITLE
nginx unit compose file: PHP Fatal error "Extension DOM is required. "

### ISSUE THREAD

**Issue by combrs** [mrsuh/php-load-test#2]
Try to docker-compose up from "cd docker/nginx-unit && docker-compose up"
built many things, warnings are scrolled out... and ended with:

Step 9/12 : RUN sh /app/bin/build.sh
 ---> Running in dac80bade983
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information                                                                                                                                  
Installing dependencies (including require-dev) from lock file                                                                                                                          
Package operations: 57 installs, 0 updates, 0 removals                                                                                                                                  
  - Installing symfony/flex (v1.1.8): Downloading (100%)                                                                                                                                
Prefetching 56 packages 
.........
Successfully built 088a2f189b47
Successfully tagged nginxunit_app:latest
Creating nginxunit_unit_1  ... done
Creating nginxunit_app_1   ... done
Creating nginxunit_unit_1  ... 
Creating nginxunit_nginx_1 ... done
Attaching to nginxunit_unit_1, nginxunit_app_1, nginxunit_nginx_1
unit_1   | 2019/03/10 10:34:59 [info] 1#1 unit started
unit_1   | 2019/03/10 10:34:59 [info] 6#6 discovery started
unit_1   | 2019/03/10 10:34:59 [notice] 6#6 module: php 7.2.10-0ubuntu0.18.04.1 "/usr/lib/unit/modules/php.unit.so"
unit_1   | 2019/03/10 10:35:00 [notice] 1#1 process 6 exited with code 0
unit_1   | 2019/03/10 10:35:00 [info] 7#7 controller started
unit_1   | 2019/03/10 10:35:00 [info] 8#8 router started
unit_1   | 2019/03/10 10:35:00 [info] 8#8 OpenSSL 1.1.0g  2 Nov 2017, 1010007f
unit_1   | 2019/03/10 10:35:00 [info] 9#9 "example_php" application started
unit_1   | 2019/03/10 10:35:00 [info] 9#9 (ABS_MODE) php script "/index.php" root: "/app/public"
unit_1   | 2019/03/10 10:35:00 [info] 10#10 "example_php" application started
unit_1   | 2019/03/10 10:35:00 [info] 10#10 (ABS_MODE) php script "/index.php" root: "/app/public"
nginxunit_app_1 exited with code 0

Wait for requests, try: curl localhost:8000, responce:

unit_1   | 2019/03/10 10:35:00 [notice] 9#9 php message: PHP Fatal error:  Uncaught RuntimeException: Extension DOM is required. in /app/vendor/symfony/config/Util/XmlUtils.php:50
unit_1   | Stack trace:
unit_1   | #0 /app/vendor/symfony/config/Util/XmlUtils.php(131): Symfony\Component\Config\Util\XmlUtils::parse('<?xml version="...', Array)
unit_1   | #1 /app/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(381): Symfony\Component\Config\Util\XmlUtils::loadFile('/app/vendor/sym...', Array)
unit_1   | #2 /app/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(45): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/app/vendor/sym...')
unit_1   | #3 /app/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php(123): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
unit_1   | #4 /app/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
unit_1   | #5 /app/ven in /app/vendor/symfony/config/Util/XmlUtils.php on line 50

**Comment by mrsuh** [comment]
Fixed it.
